client_id = "5582d70593673cec7451f29ef451590c"

name = "custom-selling-plan"
handle = "custom-selling-plan"

application_url = "https://pills-next-houston-raise.trycloudflare.com"

embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "write_products,write_purchase_options,read_orders,write_orders,write_payment_mandate,read_payment_mandate,read_payment_terms"

[auth]
redirect_urls = [
  "https://pills-next-houston-raise.trycloudflare.com/api/auth"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"
